name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  cs:
    uses: phpalto/.github/.github/workflows/CS.yml@main
    # with:
      # php-version: '8.5'
      # composer-validate: true
      # php-cs-fixer-args: '--diff --dry-run'

  sa:
    uses: phpalto/.github/.github/workflows/SA.yml@main
    # with:
      # php-version: '8.5'
      # phpstan-args: 'analyse --no-progress --memory-limit=-1'

  tests:
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3', '8.4', '8.5']
    uses: phpalto/.github/.github/workflows/tests.yml@main
    with:
      php-version: ${{ matrix.php }}
      # phpunit-args: '--colors=never'
